### ISSUE TITLE
Using TyTalk for prosody modelling for mandarin

### ISSUE THREAD

**Issue by shaynemei** [GalaxieT/TyTalk#2]
Can you help me understand what each of the values in the prosody entry mean?
e.g. ` {'proso': ((1, 1), (None, None, False))}`

**Comment by GalaxieT** [comment]
Take `{'proso': ((1, 3), (0.39, 0.37, True))}` as an example:

- `(1, 3)` marks out that the character is the _first_ character in a _3_-character-long prosodic word.
- `(0.39, 0.37, True)` is related to a relatively complex (but not quite reliable, I have to say) analysis on the pause between every two neighboring characters considering syntactic information. You can find the logic of the analysis in the function `to_marks()`. Anyway, `0.39` means that the program predicts that the degree of pause between the marked character and the next character is _0.39_. There is no absolute standard on whether _0.39_ is high or low, so  I used the average degree of pause in a sentence, _0.37_, as the standard and add it to the tuple. Under some conditions, like when the sentence is too short, such an analysis would not be triggered. When this happens, the Boolean value would turn from `True` to `False`, and the other values in the tuple would be `None`.

Some following additional tips may be helpful.
The "proso" entry is supposed to mark out the prosodic structure among the characters in a sentence. In linguistics, the prosody was classified by about three or four levels. e.g. prosodic word and prosodic phrase. In the coding of TyTalk, only two levels are considered and modeled.

**Comment by shaynemei** [comment]
That was very helpful. Thanks!
